### ISSUE TITLE
Adafruit ADXL

### ISSUE THREAD

**Issue by nicedevil007** [slebed/KingShroud#1]
Hey slebed, first I want to thank you realy much for this awesome design!

I just wanted to modify the file to allow my genuine Adafruit ADXL sensor to be mounted but can't because of not provided step files, I hope you can do an alternate version for us "Adafruit" users as well?

The hole spacing is 18.9mm.

https://www.amazon.com/Adafruit-ADXL345-Triple-Axis-Accelerometer-ADA1231/dp/B01BT4N9BC/ref=sr_1_1?crid=97X4ET0E0S83&keywords=adafruit+adxl345&qid=1648488340&sprefix=adafruit+adxl345%2Caps%2C223&sr=8-1

**Comment by slebed** [comment]
Thanks for the kind words and I'll try to get you a new version tonight.

Best,
Stephen

**Comment by slebed** [comment]
I've updated and posted a new body .STL with 18.9mm spacing
